travelGroup CRUD기능
growth-genius/travel-group-service pull request #1
Opened 2023-06-03 12:29 UTC by cyeji

2023-06-03 15:07 UTC, seunggulee1007 requested changes

2023-06-03 15:07 UTC, seunggulee1007 commented on build.gradle
> +    implementation 'com.gg.tgather:common-service:1.0.3'
최신 버전은 1.0.4입니다.
최신 버전을 유지해 주세요.

2023-06-03 15:07 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupController.java
> +
가능하면 모든 메서드에 자바 독을 남겨 주세요.

2023-06-03 15:07 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
> +    private String groupName;
필드 명 주석을 달아 주세요

2023-06-03 15:07 UTC, seunggulee1007 commented on src/test/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImplTest.java
> +        TravelGroupSaveForm travelGroupSaveForm = new TravelGroupSaveForm();
팩토리 메서드 패턴을 사용하는 것이 더 좋아 보입니다.

2023-06-03 15:20 UTC, seunggulee1007 requested changes

2023-06-03 15:20 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> +                .and(travelGroupMember.travelGroupRole.eq(TravelGroupRole.LEADER).and(travelGroupMember.accountId.eq(accountId)))).fetchFirst());
한건만 나오는 거면
fetchFirst가 아닌 fetchOne을 사용하서야 합니다.

2023-06-03 15:20 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> +    public Optional<TravelGroup> searchTravelGroupAndLeader(String groupName, String accountId) {
좀더 명확한 메서드 명을 쓰셔야 합니다.
searchByTravelGroupAndLeader와 같이 변경하시면 좋을 듯 합니다.

2023-06-03 15:30 UTC, seunggulee1007 requested changes

2023-06-03 15:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
> +        travelGroupDTO.setTotalMember(travelGroup.getTravelGroupMemberList().size());
이대로 사용할 경우 N+1의 현상이 발생할 수 있습니다.
이를 피하기 위해서 leftjoin으로 조회 이후 다시 dto를 생성해 주거나 
batch_fetch사이즈 등을 조절해서 회피할 수 있습니다.
application.yml에 
```
spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
```
혹은 자바 코드로 
```
@BatchSize(size = 3)
```
등과 같이 사용할 수 있습니다.

2023-06-03 15:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +    private static final int MAX_PARTICIPANT_COUNT = 999;
자바에서는 상수를 enum으로 표현하는 것을 권장하고 있습니다.
여기에서만 쓰이는 상수라면 내부 에넘을 선언하시는 것을 권장드립니다.

2023-06-03 15:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +        this.participantCount++;
plus할 경우, 최대 값을 넘어갔을때의 로직이 빠진 것 같습니다.

2023-06-03 15:30 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +        this.participantCount--;
minus의 경우 0 이하의 로직이 빠진 것 같습니다.
또한, 방장은 무조건 존재해야 하므로 1이하로 줄어들 수 없습니다.

2023-06-04 08:54 UTC, cyeji commented on build.gradle
> +    implementation 'com.gg.tgather:common-service:1.0.3'
넵 수정했습니다.

2023-06-04 08:54 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupController.java
> +
넵 반영했습니다.

2023-06-04 08:54 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
> +    private String groupName;
넵 수정했습니다.

2023-06-04 08:54 UTC, cyeji commented on src/test/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImplTest.java
> +        TravelGroupSaveForm travelGroupSaveForm = new TravelGroupSaveForm();
넵 변경했습니다.

2023-06-04 08:55 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> +                .and(travelGroupMember.travelGroupRole.eq(TravelGroupRole.LEADER).and(travelGroupMember.accountId.eq(accountId)))).fetchFirst());
넵 변경했습니다.

2023-06-04 08:58 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> +    public Optional<TravelGroup> searchTravelGroupAndLeader(String groupName, String accountId) {
넵 수정했습니다.

2023-06-04 09:10 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +        this.participantCount--;
네 참여자  삭제 로직 변경했습니다. 참여자 추가는 제한 수 보다 많을 경우에 추가 하지 못하도록 변경하였습니다.

2023-06-04 09:10 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +        this.participantCount++;
참여자 추가 로직 변경했습니다. 참여자 추가는 제한 수 보다 많을 경우에 추가 하지 못하도록 변경하였습니다.

2023-06-04 09:11 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
> +    private static final int MAX_PARTICIPANT_COUNT = 999;
넵 변경했습니다.

2023-06-04 09:24 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
> +        travelGroupDTO.setTotalMember(travelGroup.getTravelGroupMemberList().size());
넵 수정했습니다. 1000건으로 지정해놨습니다.

2023-06-04 09:41 UTC, seunggulee1007 approved these changes
고생하셨습니다.

2023-06-04 09:41 UTC, merged