TravelGroup,TravelGroupMember 기능 조건 컬럼 전체 변경
growth-genius/travel-group-service pull request #6
Opened 2023-06-23 06:03 UTC by cyeji

TravelGroup, TravelGroupMember 기능 API 및 서비스 id -> uuId 변경

2023-06-23 13:25 UTC, seunggulee1007 requested changes

2023-06-23 13:25 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupController.java
> +    public ApiResult<TravelGroupDto> modifyTravelGroup(@PathVariable @NotNull String travelGroupId,
Pathvariable의 경우에는 없으면 해당 url을 처음부터 찾아오지 못 합니다.
따라서 NotNull 어노테이션은 무의미 합니다.

2023-06-23 13:25 UTC, seunggulee1007 commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> -                travelGroup.id.eq(travelGroupId).and(travelGroupMember.accountId.eq(accountId)).and(travelGroupMember.travelGroupRole.eq(TravelGroupRole.LEADER)))
.and() 메서드는 가독성을 많이 해치게 됩니다. 
where 메서드는 내부적으로 BooleanExpression을 spread 형식으로 받을 수 있습니다.
때문에 BooleanExpression을 쉼표로 여러개를 작성하시는 것이 가독성에 좋습니다.
``` java
where(
    travelGroup.id.eq(travelGroupId), 
    travelGroupMember.accountId.eq(accountId)
)
```
위와 같은 식으로 사용하시면 훨씬 가독성이 좋습니다.

2023-06-24 06:02 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
> -                travelGroup.id.eq(travelGroupId).and(travelGroupMember.accountId.eq(accountId)).and(travelGroupMember.travelGroupRole.eq(TravelGroupRole.LEADER)))
넵 변경하였습니다.

2023-06-24 06:02 UTC, cyeji commented on src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupController.java
> +    public ApiResult<TravelGroupDto> modifyTravelGroup(@PathVariable @NotNull String travelGroupId,
넵 제거하였습니다.

2023-06-24 10:02 UTC, seunggulee1007 approved these changes
애쓰셨습니다.

2023-06-24 10:02 UTC, merged